name: Build documentation

on:
  # Only build the documentation once the test suite has completed on the main branch
  workflow_run:
    workflows: [Test suite]
    types: [completed]
    branches: [main]

jobs:
  build_documentation:
    name: Build documentation
    # Only run if a push to main occurred, do not run after nightly cron job
    if: ${{ github.event.workflow_run.outputs.build_docu == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup virtual python environment
        uses: ./.github/actions/setup_virtual_python_environment
      - name: Install dependencies
        run: |
          cd ${GITHUB_WORKSPACE}
          source python-workflow-venv/bin/activate
          pip install -e .[dev,fourc]
      - name: Build API documentation
        run: |
          source python-workflow-venv/bin/activate
          pdoc --math --docformat google --output-dir api-documentation src/meshpy/
      - name: Upload API documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-documentation
          path: api-documentation/
  set-flag-for-website:
    needs: build_documentation
    runs-on: ubuntu-latest
    outputs:
      build_website: ${{ steps.set.outputs.build_website }}
    steps:
      - id: set
        run: |
          if [[ "${{ github.event.workflow_run.outputs.build_docu }}" == "true" ]]; then
            echo "build_website=true" >> $GITHUB_OUTPUT
          else
            echo "build_website=false" >> $GITHUB_OUTPUT
          fi
