name: Build and deploy website

on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
  # remove on pull_request so the website is only created on main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_run:
    workflows: ["Test suite"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme myst-parser linkify-it-py
      - name: Build Sphinx website
        run: |
          sphinx-build -b html website/docs/source website/docs/build
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: website
          path: website/docs/build/

  deploy:
    environment:
      name: github-pages
      url: http://imcs-compsim.github.io/meshpy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: website
