name: Build and deploy website

on:
  # Only build and deploy the website once the testsuite is completed => coverage badge and report are necessary
  workflow_run:
    workflows: [Test suite]
    types: [completed]
    # branches: [main]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r website/requirements.txt
      - name: Build Sphinx website
        run: |
          sphinx-build -b html website/docs/source website/docs/build
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: website
          path: website/docs/build/

  deploy:
    environment:
      name: Website
      # url: http://imcs-compsim.github.io/meshpy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy coverage report to GitHub pages
        id: deploy-coverage
        uses: actions/deploy-pages@v4
        with:
          name: coverage-report
          artifact_name: coverage-report
      - name: Deploy to GitHub pages
        id: deploy-website
        uses: actions/deploy-pages@v4
        with:
          artifact_name: website
